### ISSUE TITLE
Bad Marshal Data (unknown type code)

### ISSUE THREAD

**Issue by tijanidevit** [susantabiswas/facial-login-web#9]
Traceback (most recent call last):
  File "keras_server.py", line 353, in <module>
    load_FRmodel()
  File "keras_server.py", line 94, in load_FRmodel
    model = load_model('models/model.h5', custom_objects={'triplet_loss': triplet_loss})

code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by abdou0102** [comment]
same problem

**Comment by ArshadAli-deepLearning** [comment]
same problem

**Comment by Nihal-Tiwari** [comment]
anyone able to solve this error?

**Comment by spiegel-jpg** [comment]
I am facing the same issue. Has anyone solved this?

**Comment by jeanccoelho** [comment]
https://github.com/keras-team/keras/issues/9595

**Comment by Abdulhadu** [comment]
I am facing the same issue is anyone solved this?

**Comment by spiegel-jpg** [comment]
Nope, gave up on the project.

**Comment by haripriya4work** [comment]
is this problem fixed atleast now?????? please help
